XDZIBEC

medium

# XDZIBEC-Inconsistent Type Usage in revertWithCustomError() Function Can Lead to DoS Attack

## Summary

There is a vulnerability in the `revertWithCustomError()` function arises from the inconsistent usage of types. The function attempts to use the `revert` opcode with a `bytes` type argument instead of the required string type argument. This can lead to a `(DoS) attack` as the transaction remains in a `pending` state. An attacker could exploit this bug by calling the `function` with a large `bytes` value, causing the `transaction` to `revert` but fail to complete properly, the function should be modified to use the `require` opcode, which expects a condition as the first argument and the reason for failure as a string argument

## Vulnerability Detail

```solidity
    function revertWithParsedMessage(bytes memory result) internal pure {
        (string memory revertMessage, bool hasRevertMessage) = getRevertMessage(result);

        if (hasRevertMessage) {
            revert(revertMessage);
        } else {
            revertWithCustomError(result);
        }
    }

    function revertWithCustomError(bytes memory result) internal pure {
        // referenced from https://ethereum.stackexchange.com/a/123588
        uint256 length = result.length;
        assembly {
            revert(add(result, 0x20), length)
        }
    }
}
```

The `revertWithCustomError()` function uses the `revert` opcode to `revert` the `transaction`, the `revert opcode` only takes two arguments: -the first argument is the reason for the revert, and the second argument is the length of the reason. In the `revertWithCustomError()` function, the first argument is the address of the result variable, which is a bytes type. 
an attacker can  cause a denial-of-service attack. The attacker could create a contract that calls the `revertWithCustomError()` function with a large bytes value. This would cause the r`evertWithCustomError()` function to `revert` the `transaction`, but the revert opcode would `fail` because the reason argument is not a `string` type. This would cause the transaction to be `stuck` in a` pending` state, which would prevent other transactions from being processed.
this vulnerability could be fixed by changing the `revertWithCustomError()` function to use the require opcode instead of the revert opcode. The require opcode takes two arguments: the first argument is the condition that must be met, and the second argument is the reason for the failure. If the condition is not met, the require opcode will revert the transaction and pass the reason as the reason for the revert.

## Impact

An attacker could create a contract that calls the `revertWithCustomError()` function with a large bytes value. This would cause the `revertWithCustomError()` function to` revert` the transaction, but the `revert `opcode would fail because the reason argument is not a string type. This would cause the transaction to be stuck in a pending state, which would prevent other transactions from being processed.

## Code Snippet

https://github.com/sherlock-audit/2023-04-gmx/blob/main/gmx-synthetics/contracts/error/ErrorUtils.sol#L39

## Tool used

Manual Review

## Recommendation

-changing the ` revertWithCustomError()` function to uses the `require` opcode instead of the `revert` opcode. The `require` opcode will check if the result `variable` has a length `greater` than `0`. If the result variable does not have a `length` `greater` than `0`, the `require` opcode will `revert` the transaction and pass the reason "`Error message must be provided" as the reason for the revert.`

